import { createRouter, createWebHistory } from 'vue-router'
import HelloWorld from '../components/HelloWorld.vue'

import autoGeneratedRoutes from './auto-generated-routes';

const route = [
    {
        name: 'home',
        path: '/',
        component: HelloWorld, //首页路由
    },
    {
        name: 'city',
        path: '/city',
        component: () => import('@/views/city.vue')
    },
    {
        name: 'line',
        path: '/line',
        component: () => import('@/views/line.vue')
    },
    ...autoGeneratedRoutes
]

const router = createRouter({ history: createWebHistory(), routes: route })
export default router
